env: "local"

Name: "PB Manager"
Get_Car_By_Address_URL: "some addr" # Получение данных об автомобиле по адресу
Camera:
  width: 1024           # Ширина окна с камерой
  height: 768          # Высота окна с камерой
  fps: 25              # Кадры в секунду
